version: "3"

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server:java8
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - MEMORY=2G
      - VERSION=1.12
      - TYPE=SPIGOT
      - OPS=civodulap #CHANGEZ VOTRE PSEUDO ICI
      - SPAWN_PROTECTION=0
      - VIEW_DISTANCE=16
      - SERVER_NAME=Spigot 1.12.2
      - DIFFICULTY=normal
      - MOTD=§aSpigot Minecraft Server §e1.12.2
      - SERVER_IP=0.0.0.0
      - EXEC_DIRECTLY=true
      - STOP_SERVER_ANNOUNCE_DELAY=10
      - ENABLE_COMMAND_BLOCK=true
      - USE_AIKAR_FLAGS=true
      - ONLINE_MODE=FALSE
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./server:/data
